### ISSUE TITLE
Error while trying to boot using ks-libvirt

### ISSUE THREAD

**Issue by bioinfornatics** [cmadamsgit/ks-install#2]
@cmadamsgit Thanks for your tool,

I am actually stuck on this error
![ks-libvirt-error](https://user-images.githubusercontent.com/491720/174902317-f876f17d-46fa-45c9-803a-125bb2251628.png)

The kickstart is
```
# Generated by pykickstart v3.36
#version=DEVEL
# Keyboard layouts
keyboard --vckeymap=fr --xlayouts='fr'
#Root password
rootpw --lock
# System language
lang fr_FR.UTF-8
# Realm or domain membership
realm join --server-software=freeipa --client-software=sssd ipa.foo.fr
# Reboot after installation
reboot
# Use text mode install
text
# Network information
network  --bootproto=dhcp --device=eth0 --nameserver=10.0.0.1 --noipv6 --activate
# Firewall configuration
firewall --enabled --service=ssh,ntp
# Use network installation
url --metalink="https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64"
repo --name="fedora" --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch
repo --name="updates" --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f$releasever&arch=$basearch
# System timezone
timezone Europe/Paris --utc
# Run the Setup Agent on first boot
firstboot --reconfig
# SELinux configuration
selinux --enforcing
# System bootloader configuration
bootloader --location=mbr 
# Clear the Master Boot Record
zerombr
# Partition clearing information
clearpart --all --initlabel
# Disk partitioning information
part btrfs.boot --asprimary --fstype="btrfs" --size=1024 --label=boot
part btrfs.main --fstype="btrfs" --grow --encrypted
btrfs /boot --label=fedora-boot btrfs.boot
btrfs none --label=fedora-btrfs.main btrfs.main
btrfs / --subvol --name=root fedora-btrfs.main
btrfs /etc --subvol --name=etc fedora-btrfs.main
btrfs /var --subvol --name=var fedora-btrfs.main
btrfs /opt --subvol --name=opt fedora-btrfs.main
btrfs /home --subvol --name=home fedora-btrfs.main

%post

ipa-client-install  \
                   --mkhomedir \
                   --ntp-server=ipa.foo.fr \
                   --ssh-trust-dns

# boot in graphical mode
systemctl set-default graphical.target
%end

%packages
@^cloud-management
freeipa-client
initial-setup
neovim
zram-generator
zram-generator-defaults

%end
```
and below the command to create the vm
```
sudo ks-libvirt --verbose --os fedora36 --name fedora-rawhide --disk 10 --ssh -a src/custom-fedora-36-ks.cfg --net virbr0
```

Thanks for your help

**Comment by cmadamsgit** [comment]
Hmm, I'm not sure. I have seen weird errors from issues loading the inirtd image though. Can you try using more RAM for the VM to see if that helps? The default is 2048 (2G), which I think should be enough for Fedora 36, but try "--ram 4096".

Another thing to try is to remove the double quotes around the URL on the url line. I'm not sure I handle that correctly today (although I believe that if that were the problem, the VM wouldn't boot because it also wouldn't have a kernel).

One thing for more debugging would be to add "--serial", which should create a VM with a serial console rather than a GUI - you can capture the output to see where the errors started (in case there's more information before the repeating error above).

**Comment by bioinfornatics** [comment]
Thanks, @cmadamsgit, for your precious help. 

I am trying to perform some empiric test in order to found the origin of my issue. So with time I will fix it.

As I can confirm that your test example works fine with `--ram 4096`. I close this issue

Thanks again
Have a nice day
